version: '3.9'
services:
  notesbackend:
    container_name: notesbackend
    image: notesbackend
    build: 
      context: ./backend
      dockerfile: notes.dockerfile
    ports:
      - 4001:4001
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db1:5432/postgres?schema=public

  db1:
    container_name: db1
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}